"""
Orchestration script for running cardiac electrophysiology simulations (MonoAlg3D)
with fibrosis patterns generated by the GNT Framework or pre-existing meshes.

This script manages the entire pipeline:
1. Sets up simulation parameters.
2. Checks for previously completed simulations to avoid redundant work.
3. Optionally generates fibrosis meshes (.alg files) using the GNT Framework (Octave).
4. Configures and runs the MonoAlg simulator.
5. Parses the results and logs them to a comprehensive CSV file.
"""
import os
import subprocess
import configparser
import logging
import argparse
import shutil
import numpy as np
import pandas as pd
from datetime import datetime
from pathlib import Path

# --- PATH CONFIGURATION ---
CWD = Path.cwd()
OCTAVE_SCRIPT_DIR = CWD / "perlin-fibrosis-generator"

# --- HELPER CLASSES AND FUNCTIONS ---
# Custom ConfigParser to preserve case sensitivity of keys
class CasePreservingConfigParser(configparser.ConfigParser):
    def optionxform(self, optionstr):
        return optionstr

def setup_logging(log_file=None):
    """Configures logging to console and optionally to a file."""
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.INFO)

    if root_logger.hasHandlers():
        root_logger.handlers.clear()

    formatter = logging.Formatter(
        '%(asctime)s - %(levelname)s - %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )

    # Console Handler
    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    root_logger.addHandler(console_handler)

    # File Handler
    if log_file:
        log_path = Path(log_file)
        log_path.parent.mkdir(parents=True, exist_ok=True)

        file_handler = logging.FileHandler(log_path, mode='w')
        file_handler.setFormatter(formatter)
        root_logger.addHandler(file_handler)

        logging.info(f"Log file configured at: {log_path.resolve()}")

def load_completed_simulations(results_csv_path):
    """Loads the results CSV to check for completed simulations."""
    if not results_csv_path.is_file():
        # Create file with header
        results_csv_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(columns=[
            'fibrosis_type', 'fiber_angle_deg', 'density', 'seed', 'atpi', 'final_time_ms'
        ]).to_csv(results_csv_path, index=False)
    return pd.read_csv(results_csv_path)

def is_simulation_done(df, params):
    """Checks if a simulation with the given parameters is already in the DataFrame."""
    # Convert params to query string
    query_parts = []
    for k, v in params.items():
        if isinstance(v, (int, float)):
             query_parts.append(f"`{k}` == {v}")
        else:
             query_parts.append(f"`{k}` == '{v}'")

    query = ' & '.join(query_parts)
    return not df.query(query).empty

def check_existing_meshes(fibrosis_type, angles, densities, seeds, meshes_dir):
    """Verifies that all expected .alg mesh files exist. Returns True if all required meshes are found, False otherwise."""
    missing_files = []
    f_mesh_dir = meshes_dir / fibrosis_type

    for angle_deg in angles:
        for density in densities:
            for seed in seeds:
                mesh_file = f_mesh_dir / f"{fibrosis_type}_angle{angle_deg}_density{density:.2f}_seed{seed}.alg"
                if not mesh_file.is_file():
                    missing_files.append(mesh_file)

    if missing_files:
        logging.error("Missing required meshes:")
        for f in missing_files[:5]:
            logging.error(f"  - {f.name}")
        if len(missing_files) > 5:
            logging.error(f"... and {len(missing_files)-5} more.")
        return False

    logging.info(f"All required meshes found in: {f_mesh_dir}")
    return True

def generate_fibrosis_mesh(mesh_config, output_batch_dir):
    """Calls the GNT Framework to generate the .alg file."""
    # Extract Mesh Configuration
    f_type = mesh_config["fibrosis_type"]
    angle_deg = mesh_config["angle_deg"]
    density = mesh_config["density"]
    seed = mesh_config["seed"]
    dim_mode = mesh_config["dim_mode"]
    domain_vec = mesh_config["domain_dims"]
    shape = mesh_config["shape"]
    core_vec = mesh_config["core_dims"]

    # Construct Output Path
    # Structure: alg_meshes/compact/compact_angle0_density0.40_seed123
    output_dir = output_batch_dir / f_type
    filename_no_ext = f"{f_type}_angle{angle_deg}_density{density:.2f}_seed{seed}"
    full_output_path = output_dir / filename_no_ext
    final_mesh_path = full_output_path.with_suffix(full_output_path.suffix + ".alg")

    # Skip if exists
    if final_mesh_path.exists():
        logging.info(f"Skipping generation, mesh exists: {final_mesh_path.name}")
        return str(final_mesh_path)

    logging.info(f"Generating mesh: {final_mesh_path.name}")

    domain_str = ','.join(map(str, domain_vec))
    core_str = ','.join(map(str, core_vec)) if core_vec else ''

    octave_cmd = (f"run_fibrosis_generator('{f_type}', {density}, {seed}, {angle_deg}, '{dim_mode}', [{domain_str}], '{shape}', [{core_str}], '{str(full_output_path)}', true, false);")
    cmd = ["octave-cli", "-W", "-q", "--no-gui", "--eval", octave_cmd]

    try:
        logging.info(f"Executing Octave command for mesh generation...")
        subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=str(OCTAVE_SCRIPT_DIR))
    except subprocess.CalledProcessError as e:
        logging.error(f"Octave execution failed!")
        logging.error(f"STDOUT: {e.stdout}")
        logging.error(f"STDERR: {e.stderr}")
        raise e

    return str(final_mesh_path)

def configure_and_run_simulation(mesh_path, sim_output_dir, sim_params, batch_dir, base_config_path):
    """Configures the .ini file and runs the MonoAlg3D simulation."""
    sim_output_dir.mkdir(parents=True, exist_ok=True)

    ftype = sim_params['fibrosis_type']
    angle_deg = sim_params['fiber_angle_deg']
    density = sim_params['density']
    seed = sim_params['seed']
    atpi_value = sim_params['atpi']

    # Parse ALG header for discretization
    with open(mesh_path, 'r') as f:
        first_line = f.readline()
        lines_count = sum(1 for _ in f) + 1 # +1 for the line we just read

        parts = first_line.split(',')
        # Column 3 (0-index 3) is dx/2 in GNT output format
        half_dx = float(parts[3].strip())
        num_extra_fields = len(parts) - 6

    # Construct simulation name and ECG file path
    simulation_name = f"{ftype} angle={angle_deg} den={density} seed={seed} atpi={atpi_value}"
    ecg_file_path = sim_output_dir / "ecg.txt"

    # Configure .ini
    config = CasePreservingConfigParser()
    config.read(base_config_path)
    config['domain']['mesh_file'] = str(mesh_path)
    config['domain']['num_volumes'] = str(lines_count)
    config['domain']['original_discretization'] = str(half_dx * 2)
    config['domain']['num_extra_fields'] = str(num_extra_fields)
    config['domain']['name'] = simulation_name
    config['save_result']['output_dir'] = str(sim_output_dir)
    config['extra_data']['atpi'] = str(atpi_value)
    config['calc_ecg']['filename'] = str(ecg_file_path)

    ini_path = batch_dir / "configs" / f"{ftype}.ini"
    with open(ini_path, 'w') as configfile:
        config.write(configfile)

    # Execute the simulation with MonoAlg3D
    logging.info(f"Running MonoAlg3D with config: {ini_path.name}")
    monoalg_exe = CWD / "bin" / "MonoAlg3D"
    command = [str(monoalg_exe), "-c", str(ini_path)]

    try:
        subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        logging.error(f"MonoAlg3D failed for {simulation_name}.")
        logging.error(f"Stderr: {e.stderr}")
        raise e

def parse_simulation_log(sim_output_dir):
    """Parses outputlog.txt for final time."""
    simulation_log_file = sim_output_dir / "outputlog.txt"
    if not simulation_log_file.is_file():
        logging.warning(f"Log file not found: {simulation_log_file}")
        return -1.0

    last_t = 0.0
    with open(simulation_log_file, 'r') as f:
        for line in f:
            if line.startswith('t = '):
                try:
                    # t = 1000, Vm_max = ...
                    t_value = float(line.split(',')[0].split('=')[1].strip())
                    if t_value > last_t:
                        last_t = t_value
                except (IndexError, ValueError):
                    logging.error(f"Failed to parse log file {simulation_log_file.name} line: {line.strip()}")
                    raise

    logging.info(f"Simulation finished. Final time: {last_t} ms.")
    return last_t

def run_simulation_batch(batch_params):
    """Runs a batch of simulations for given parameters."""

    angles = batch_params['angles']
    densities = batch_params['densities']
    seeds = batch_params['seeds']
    mesh_config = batch_params['mesh_config']
    atpi_vals = batch_params['atpi_vals']
    generate_mesh = batch_params['generate_mesh']
    batch_dir = batch_params['batch_dir']
    base_config_path = batch_params['base_config_path']

    fibrosis_type = mesh_config["fibrosis_type"]

    # --- DYNAMIC DIRECTORY SETUP (Based on ATPI) ---
    outputs_dir = batch_dir / "outputs"
    alg_meshes_dir = batch_dir / "alg_meshes"

    batch_params['outputs_dir'] = outputs_dir
    batch_params['alg_meshes_dir'] = alg_meshes_dir

    results_csv_path = batch_dir / "analysis" / "simulation_results.csv"

    # Load History
    completed_df = load_completed_simulations(results_csv_path)
    logging.info(f"Loaded {len(completed_df)} completed simulations from history.")

    if not generate_mesh:
        logging.info("Mesh generation not requested. Verifying existing meshes...")
        if not check_existing_meshes(fibrosis_type, angles, densities, alg_meshes_dir):
            logging.error("Aborting. Use --generate_mesh flag to create missing meshes.")
            return

    # --- BATCH LOOP ---
    for atpi_val in atpi_vals:
        logging.info(f"Starting batch for ATPI = {atpi_val}")

        for angle_deg in angles:
            logging.info(f"Processing angle: {angle_deg} degrees")

            for density in densities:
                density = round(density, 2)

                for seed in seeds:
                    # Check if done
                    sim_params = {
                        'fibrosis_type': fibrosis_type,
                        'fiber_angle_deg': angle_deg,
                        'density': density,
                        'seed': seed,
                        'atpi': atpi_val
                    }

                    if is_simulation_done(completed_df, sim_params):
                        logging.info(f"Skipping done: {fibrosis_type} angle={angle_deg} den={density} seed={seed}")
                        continue

                    logging.info(f"Starting simulation: {fibrosis_type} angle={angle_deg} den={density} seed={seed}")

                    # 1. Get Mesh
                    mesh_config["angle_deg"] = angle_deg
                    mesh_config["density"] = density
                    mesh_config["seed"] = seed
                    if generate_mesh:
                        mesh_path = generate_fibrosis_mesh(mesh_config, alg_meshes_dir)
                    else:
                        mesh_path = alg_meshes_dir / fibrosis_type / f"{fibrosis_type}_angle{angle_deg}_density{density:.2f}_seed{seed}.alg"
                    mesh_config["mesh_path"] = mesh_path

                    # 2. Run Simulation
                    sim_out_dir = outputs_dir / f"atpi{atpi_val}" / f"{fibrosis_type}_angle{angle_deg}" / f"den{density}_seed{seed}"
                    configure_and_run_simulation(mesh_path, sim_out_dir, sim_params, batch_dir, base_config_path)

                    # 3. Log Result
                    final_time = parse_simulation_log(sim_out_dir)
                    if final_time >= 0:
                        result_data = sim_params.copy()
                        result_data['final_time_ms'] = final_time

                        # Append to CSV immediately
                        pd.DataFrame([result_data]).to_csv(results_csv_path, mode='a', header=False, index=False)
                        # Update local DF to avoid re-running if script crashes and restarts
                        completed_df = pd.concat([completed_df, pd.DataFrame([result_data])], ignore_index=True)

                        logging.info(f"Finished seed {seed}. Final Simulation Time: {final_time} ms")
                logging.info(f"Simulations completed for density {density}.")
            logging.info(f"Simulations completed for all densities at angle {angle_deg}.")
        logging.info(f"Simulations completed for all angles for ATPI = {atpi_val}.")
    logging.info("Batch Completed.")

# --- SCRIPT ENTRY POINT ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Orchestrator for MonoAlg3D with GNT Fibrosis Generation Framework.")

    # Required Arguments
    parser.add_argument("--ftype", type=str, required=True, choices=['compact', 'interstitial', 'diffuse', 'patchy'], help="Fibrosis type.")
    parser.add_argument("--base_config", type=str, required=True, help="Path to base configuration .ini file.")

    # Optional Configuration Arguments
    parser.add_argument("--batch_dir", type=str, default=f"simulation_batches_{datetime.now().strftime('%Y%m%d_%H%M%S')}", help="Base directory for configurations and results.")
    parser.add_argument("--angles", type=int, nargs='+', default=[0, 30, 60, 90], help="List of fiber angles in degrees.")
    parser.add_argument("--min_den", type=float, default=0.1, help="Minimum fibrosis density.")
    parser.add_argument("--max_den", type=float, default=0.9, help="Maximum fibrosis density.")
    parser.add_argument("--num_seeds", type=int, default=100, help="Number of random seeds to simulate.")
    parser.add_argument("--atpi_vals", type=float, nargs='+', default=[2.0], help="List of ATPI values.")
    parser.add_argument("--generate_mesh", action="store_true", help="Generate meshes via Octave GNT.")
    parser.add_argument("--dim_mode", type=str, default="2D", choices=["2D", "3D"], help="Dimension mode.")
    parser.add_argument("--shape", type=str, default="full", help="Geometric shape (ellipse, box, full, etc).")
    parser.add_argument("--domain_dims", type=float, nargs='+', default=[0.01, 4.0, 4.0, 0.0], help="Vector [dx, Lx, Ly, (Lz)].")
    parser.add_argument("--core_dims", type=float, nargs='+', default=[], help="Vector [width, height, depth].")
    parser.add_argument("--log_file", action="store_true", help="Enable logging to a file in addition to console.")

    # Parse Arguments
    args = parser.parse_args()

    # Prepare base directory path
    batch_dir = CWD / args.batch_dir / args.dim_mode / args.shape
    batch_dir.mkdir(parents=True, exist_ok=True)

    # Setup Logging
    log_file_path = None
    if args.log_file:
        log_file_path = batch_dir / f"log.txt"
    setup_logging(log_file=log_file_path)

    # Verify base configuration file exists
    base_config_path = Path(args.base_config)
    if not base_config_path.is_file():
        logging.error(f"Base configuration file not found: {base_config_path}")
        exit(1)

    # Copy base configuration file to batch_dir/configs as base_simulation_config.ini
    dest_base_config_path = batch_dir / "configs" / "base_simulation_config.ini"
    dest_base_config_path.parent.mkdir(parents=True, exist_ok=True)
    if not dest_base_config_path.is_file():
        shutil.copy(base_config_path, dest_base_config_path)
    base_config_path = dest_base_config_path

    # Range of densities to simulate
    density_step = 0.05
    simulation_densities = np.arange(args.max_den, args.min_den - density_step, -density_step)

    # Seeds
    master_seed = 20260101 # Happy New Year 2026!
    rng = np.random.default_rng(master_seed)
    seeds = rng.integers(low=1, high=9999999999, size=args.num_seeds).tolist()

    # Build Meshes Configuration
    mesh_config = {}
    mesh_config["fibrosis_type"] = args.ftype
    mesh_config["dim_mode"] = args.dim_mode
    mesh_config["shape"] = args.shape
    mesh_config["domain_dims"] = args.domain_dims
    mesh_config["core_dims"] = args.core_dims

    # If shape is 'full', override core dimensions to empty
    if args.shape.lower() == "full":
        mesh_config["core_dims"] = []

    # Log
    logging.info(f"Base directory set to: {batch_dir.resolve()}")
    logging.info(f"Using base configuration file: {Path(args.base_config).name}")
    logging.info(f"Copied base configuration file to: {dest_base_config_path.resolve()}")
    logging.info(f"Densities to simulate: {simulation_densities}")
    logging.info(f"Number of seeds: {args.num_seeds}")
    logging.info(f"Master seed: {master_seed}")
    logging.info(f"Seeds: {seeds}")
    logging.info(f"Meshes Configuration: {mesh_config}")
    logging.info(f"---- Starting Batch Simulations ----")

    # Batch Parameters
    batch_params = {
        'angles': args.angles,
        'densities': simulation_densities,
        'seeds': seeds,
        'mesh_config': mesh_config,
        'atpi_vals': args.atpi_vals,
        'generate_mesh': args.generate_mesh,
        'batch_dir': batch_dir,
        'base_config_path': base_config_path
    }

    # Run Batch Simulations
    run_simulation_batch(batch_params)
