"""
Orchestration script for running cardiac electrophysiology simulations (MonoAlg3D)
with fibrosis patterns generated by the GNT Framework or pre-existing meshes.

This script manages the entire pipeline:
1. Sets up simulation parameters.
2. Checks for previously completed simulations to avoid redundant work.
3. Optionally generates fibrosis meshes (.alg files) using the GNT Framework (Octave).
4. Configures and runs the MonoAlg simulator.
5. Parses the results and logs them to a comprehensive CSV file.
"""
import os, subprocess, configparser, logging, argparse, shutil, sys, time
import numpy as np
import pandas as pd
from datetime import datetime
from pathlib import Path

# --- PATH CONFIGURATION ---
CWD = Path.cwd()
OCTAVE_SCRIPT_DIR = CWD / "perlin-fibrosis-generator"

# --- HELPER CLASSES AND FUNCTIONS ---
# Custom ConfigParser to preserve case sensitivity of keys
class CasePreservingConfigParser(configparser.ConfigParser):
    def optionxform(self, optionstr):
        return optionstr

def setup_logging(log_file=None):
    """
    Configures logging to console and optionally to a file:
    - Console (INFO+): Clean summary, no clutter.
    - File (DEBUG+): Detailed audit trail of every seed.
    """
    root_logger = logging.getLogger()
    root_logger.setLevel(logging.DEBUG)

    if root_logger.hasHandlers():
        root_logger.handlers.clear()

    # --- Console Handler ---
    console_fmt = logging.Formatter('%(asctime)s | %(levelname)-7s | %(message)s', datefmt='%H:%M:%S')
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(console_fmt)
    console_handler.setLevel(logging.INFO) # Just show INFO, WARNING, ERROR
    root_logger.addHandler(console_handler)

    # --- 2. File Handler (Detailed) ---
    if log_file:
        log_path = Path(log_file)
        log_path.parent.mkdir(parents=True, exist_ok=True)

        file_fmt = logging.Formatter(
            '%(asctime)s - %(levelname)s - %(message)s',
            datefmt='%Y-%m-%d %H:%M:%S'
        )
        file_handler = logging.FileHandler(log_path, mode='w')
        file_handler.setFormatter(file_fmt)
        file_handler.setLevel(logging.DEBUG)
        root_logger.addHandler(file_handler)

        root_logger.debug(f"Log file configured at: {log_path.resolve()}")

def print_progress(iteration, total, prefix='', suffix='', decimals=1, length=40):
    """
    Adaptive progress indicator:
    - Desktop (Interactive Terminal): Animated bar.
    - Cluster (Non-interactive/File): Discrete logs every 10%.
    """
    # Check if we are in a real terminal
    is_interactive = sys.stdout.isatty()

    percent_float = 100 * (iteration / float(total))
    percent_str = ("{0:." + str(decimals) + "f}").format(percent_float)

    if is_interactive:
        filled_length = int(length * iteration // total)
        bar = '█' * filled_length + '-' * (length - filled_length)
        sys.stdout.write(f'\r{prefix}  |{bar}| {percent_str}% {suffix}')
        if iteration == total:
            sys.stdout.write('\n')
        sys.stdout.flush()

    else:
        should_print = (iteration == 1) or (iteration == total) or (iteration % (max(1, total // 10)) == 0)

        if should_print:
            logging.info(f"{prefix} Progress: {iteration}/{total} ({percent_str}%) {suffix}")

def load_completed_simulations(results_csv_path):
    """Loads the results CSV to check for completed simulations."""
    if not results_csv_path.is_file():
        results_csv_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(columns=[
            'fibrosis_type', 'fiber_angle_deg', 'density', 'seed', 'atpi', 'final_time_ms'
        ]).to_csv(results_csv_path, index=False)
        logging.debug(f"Created new results file at: {results_csv_path}")

    df = pd.read_csv(results_csv_path)
    logging.debug(f"Loaded history: {len(df)} simulations found.")
    return df

def is_simulation_done(df, params):
    """Checks if a simulation with the given parameters is already in the DataFrame."""
    # Convert params to query string
    query_parts = []
    for k, v in params.items():
        if isinstance(v, (int, float)):
             query_parts.append(f"`{k}` == {v}")
        else:
             query_parts.append(f"`{k}` == '{v}'")

    query = ' & '.join(query_parts)
    return not df.query(query).empty

def check_existing_meshes(fibrosis_type, angles, densities, seeds, meshes_dir):
    """Verifies that all expected .alg mesh files exist. Returns True if all required meshes are found, False otherwise."""
    missing_files = []
    f_mesh_dir = meshes_dir / fibrosis_type

    for angle_deg in angles:
        for density in densities:
            for seed in seeds:
                mesh_file = f_mesh_dir / f"{fibrosis_type}_angle{angle_deg}_density{density:.2f}_seed{seed}.alg"
                if not mesh_file.is_file():
                    missing_files.append(mesh_file)

    if missing_files:
        logging.error("Missing required meshes:")
        for f in missing_files[:5]:
            logging.error(f"  - {f.name}")
        if len(missing_files) > 5:
            logging.error(f"... and {len(missing_files)-5} more.")
        return False

    logging.info(f"Integrity Check: All {len(angles)*len(densities)*len(seeds)} required meshes found.")
    return True

def generate_fibrosis_mesh(mesh_config, output_batch_dir):
    """Calls the GNT Framework to generate the .alg file."""
    # Extract Mesh Configuration
    f_type = mesh_config["fibrosis_type"]
    angle_deg = mesh_config["angle_deg"]
    density = mesh_config["density"]
    seed = mesh_config["seed"]
    dim_mode = mesh_config["dim_mode"]
    domain_vec = mesh_config["domain_dims"]
    shape = mesh_config["shape"]
    core_vec = mesh_config["core_dims"]

    # Construct Output Path
    # Structure: alg_meshes/compact/compact_angle0_density0.40_seed123
    output_dir = output_batch_dir / f_type
    filename_no_ext = f"{f_type}_angle{angle_deg}_density{density:.2f}_seed{seed}"
    full_output_path = output_dir / filename_no_ext
    final_mesh_path = full_output_path.with_suffix(full_output_path.suffix + ".alg")

    # Skip if exists
    if final_mesh_path.exists():
        logging.debug(f"Mesh already exists: {final_mesh_path.name}")
        return str(final_mesh_path)

    logging.debug(f"Generating mesh via Octave: {final_mesh_path.name}")

    domain_str = ','.join(map(str, domain_vec))
    core_str = ','.join(map(str, core_vec)) if core_vec else ''

    octave_cmd = (f"run_fibrosis_generator('{f_type}', {density}, {seed}, {angle_deg}, '{dim_mode}', [{domain_str}], '{shape}', [{core_str}], '{str(full_output_path)}', true, false);")
    cmd = ["octave-cli", "-W", "-q", "--no-gui", "--eval", octave_cmd]

    try:
        logging.debug(f"Calling subprocess: {' '.join(cmd)}")
        subprocess.run(cmd, check=True, capture_output=True, text=True, cwd=str(OCTAVE_SCRIPT_DIR))
    except subprocess.CalledProcessError as e:
        logging.error(f"Octave execution failed for seed {seed}!")
        logging.error(f"STDOUT: {e.stdout}")
        logging.error(f"STDERR: {e.stderr}")
        raise e

    return str(final_mesh_path)

def configure_and_run_simulation(mesh_path, sim_output_dir, sim_params, batch_dir, base_config_path):
    """Configures the .ini file and runs the MonoAlg3D simulation."""
    sim_output_dir.mkdir(parents=True, exist_ok=True)

    ftype = sim_params['fibrosis_type']
    angle_deg = sim_params['fiber_angle_deg']
    density = sim_params['density']
    seed = sim_params['seed']
    atpi_value = sim_params['atpi']

    # Parse ALG header for discretization
    with open(mesh_path, 'r') as f:
        first_line = f.readline()
        lines_count = sum(1 for _ in f) + 1 # +1 for the line we just read

        parts = first_line.split(',')
        # Column 3 (0-index 3) is dx/2 in GNT output format
        half_dx = float(parts[3].strip())
        num_extra_fields = len(parts) - 6

    # Construct simulation name and ECG file path
    simulation_name = f"{ftype} angle={angle_deg} den={density} seed={seed} atpi={atpi_value}"
    ecg_file_path = sim_output_dir / "ecg.txt"

    # Configure .ini
    config = CasePreservingConfigParser()
    config.read(base_config_path)
    config['domain']['mesh_file'] = str(mesh_path)
    config['domain']['num_volumes'] = str(lines_count)
    config['domain']['original_discretization'] = str(half_dx * 2)
    config['domain']['num_extra_fields'] = str(num_extra_fields)
    config['domain']['name'] = simulation_name
    config['save_result']['output_dir'] = str(sim_output_dir)
    config['extra_data']['atpi'] = str(atpi_value)
    config['calc_ecg']['filename'] = str(ecg_file_path)

    ini_path = batch_dir / "configs" / f"{ftype}.ini"
    with open(ini_path, 'w') as configfile:
        config.write(configfile)

    # Execute the simulation with MonoAlg3D
    monoalg_exe = CWD / "bin" / "MonoAlg3D"
    command = [str(monoalg_exe), "-c", str(ini_path)]

    logging.debug(f"Launching MonoAlg3D: {ini_path.name}")
    logging.debug(f"Command: {' '.join(command)}")

    try:
        subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as e:
        logging.error(f"MonoAlg3D failed for {sim_params['fibrosis_type']} seed {sim_params['seed']}.")
        logging.error(f"Stderr: {e.stderr}")
        raise e

def parse_simulation_log(sim_output_dir):
    """Parses outputlog.txt for final time."""
    simulation_log_file = sim_output_dir / "outputlog.txt"
    if not simulation_log_file.is_file():
        logging.error(f"Output log not found: {simulation_log_file}")
        return -1.0

    last_t = 0.0
    with open(simulation_log_file, 'r') as f:
        for line in f:
            if line.startswith('t = '):
                try:
                    # t = 1000, Vm_max = ...
                    t_value = float(line.split(',')[0].split('=')[1].strip())
                    if t_value > last_t:
                        last_t = t_value
                except (IndexError, ValueError):
                    logging.error(f"Parse error in {simulation_log_file.name}: {line.strip()}")
                    raise

    logging.debug(f"Parsed final time: {last_t} ms from {simulation_log_file.name}")
    return last_t

def run_simulation_batch(batch_params):
    """Runs a batch of simulations for given parameters."""

    # Unpack parameters
    angles = batch_params['angles']
    densities = batch_params['densities']
    seeds = batch_params['seeds']
    mesh_config = batch_params['mesh_config']
    atpi_vals = batch_params['atpi_vals']
    generate_mesh = batch_params['generate_mesh']
    batch_dir = batch_params['batch_dir']
    base_config_path = batch_params['base_config_path']
    fibrosis_type = mesh_config["fibrosis_type"]

    # Setup directories
    outputs_dir = batch_dir / "outputs"
    alg_meshes_dir = batch_dir / "alg_meshes"
    results_csv_path = batch_dir / "analysis" / "simulation_results.csv"

    # Load history of completed simulations
    completed_df = load_completed_simulations(results_csv_path)

    # Visual header
    logging.info("="*60)
    logging.info(f"STARTING BATCH: {fibrosis_type.upper()}")
    logging.info(f"Configurations: {len(atpi_vals)} ATPIs x {len(angles)} Angles x {len(densities)} Densities")
    logging.info(f"Seeds per Config: {len(seeds)}")
    logging.info("="*60)

    if not generate_mesh:
        if not check_existing_meshes(fibrosis_type, angles, densities, alg_meshes_dir):
            logging.error("Aborting. Use --generate_mesh flag to create missing meshes.")
            return

    total_configs = len(atpi_vals) * len(angles) * len(densities)
    config_counter = 0

    # --- BATCH LOOP ---
    logging.info(f"---- Starting Batch Simulations ----")
    for atpi_val in atpi_vals:
        logging.info(f"Starting batch for ATPI = {atpi_val}")

        for angle_deg in angles:
            logging.info(f"Processing angle: {angle_deg} degrees")

            for density in densities:
                density = round(density, 2)
                config_counter += 1

                # Block header
                header_msg = f"[{config_counter}/{total_configs}] Config: ATPI={atpi_val} | Angle={angle_deg}° | Density={density:.2f}"
                logging.info(header_msg)

                # Counters
                skipped = 0
                processed = 0
                errors = 0
                start_time = time.time()

                for i, seed in enumerate(seeds):
                    sim_params = {
                        'fibrosis_type': fibrosis_type,
                        'fiber_angle_deg': angle_deg,
                        'density': density,
                        'seed': seed,
                        'atpi': atpi_val
                    }

                    # Update progress bar
                    suffix_info = f"(Run: {processed}, Skip: {skipped}, Err: {errors})"
                    print_progress(i + 1, len(seeds), prefix="Processing seeds:", suffix=suffix_info, length=30)

                    logging.debug(f"SEED {seed}: Checking status...")

                    if is_simulation_done(completed_df, sim_params):
                        skipped += 1
                        logging.debug(f"SEED {seed}: Skipped (Simulation already done)")
                        continue

                    try:
                        # 1. Mesh Config
                        mesh_config["angle_deg"] = angle_deg
                        mesh_config["density"] = density
                        mesh_config["seed"] = seed

                        if generate_mesh:
                            mesh_path = generate_fibrosis_mesh(mesh_config, alg_meshes_dir)
                        else:
                            mesh_path = alg_meshes_dir / fibrosis_type / f"{fibrosis_type}_angle{angle_deg}_density{density:.2f}_seed{seed}.alg"

                        # 2. Run Simulation
                        sim_out_dir = outputs_dir / f"atpi{atpi_val}" / f"{fibrosis_type}_angle{angle_deg}" / f"den{density}_seed{seed}"
                        configure_and_run_simulation(mesh_path, sim_out_dir, sim_params, batch_dir, base_config_path)

                        # 3. Parse & Save
                        final_time = parse_simulation_log(sim_out_dir)

                        if final_time >= 0:
                            result_data = sim_params.copy()
                            result_data['final_time_ms'] = final_time

                            pd.DataFrame([result_data]).to_csv(results_csv_path, mode='a', header=False, index=False)
                            new_row = pd.DataFrame([result_data])
                            completed_df = pd.concat([completed_df, new_row], ignore_index=True)

                            processed += 1
                            logging.debug(f"SEED {seed}: Success (Sim finished: {final_time} ms)")
                        else:
                            errors += 1
                            logging.warning(f"SEED {seed}: Invalid result (check debug log)")

                    except Exception as e:
                        errors += 1
                        logging.error(f"SEED {seed}: Failed - {str(e)}")

                elapsed = time.time() - start_time
                logging.info(f"   > Done in {elapsed:.1f}s. Results: {processed} new, {skipped} skipped, {errors} errors.")
                logging.info("-" * 40)

    logging.info("="*60)
    logging.info("BATCH COMPLETED SUCCESSFULLY")
    logging.info("="*60)

# --- SCRIPT ENTRY POINT ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Orchestrator for MonoAlg3D with GNT Fibrosis Generation Framework.")

    # Required Arguments
    parser.add_argument("--ftype", type=str, required=True, choices=['compact', 'interstitial', 'diffuse', 'patchy'], help="Fibrosis type.")
    parser.add_argument("--base_config", type=str, required=True, help="Path to base configuration .ini file.")

    # Optional Configuration Arguments
    parser.add_argument("--batch_dir", type=str, default=f"simulation_batches_{datetime.now().strftime('%Y%m%d_%H%M%S')}", help="Base directory for configurations and results.")
    parser.add_argument("--angles", type=int, nargs='+', default=[0, 30, 60, 90], help="List of fiber angles in degrees.")
    parser.add_argument("--min_den", type=float, default=0.1, help="Minimum fibrosis density (0.0 to 1.0).")
    parser.add_argument("--max_den", type=float, default=0.9, help="Maximum fibrosis density (0.0 to 1.0).")
    parser.add_argument("--dens_step", type=float, default=0.05, help="Step size for fibrosis density (0.0 to 1.0).")
    parser.add_argument("--densities", type=float, nargs='+', default=[], help="Explicit list of densities to simulate (0.0 to 1.0).")
    parser.add_argument("--num_seeds", type=int, default=100, help="Number of random seeds to simulate.")
    parser.add_argument("--atpi_vals", type=float, nargs='+', default=[2.0], help="List of ATPI values.")
    parser.add_argument("--generate_mesh", action="store_true", help="Generate meshes via Octave GNT.")
    parser.add_argument("--dim_mode", type=str, default="2D", choices=["2D", "3D"], help="Dimension mode.")
    parser.add_argument("--shape", type=str, default="full", help="Geometric shape (ellipse, box, full, etc).")
    parser.add_argument("--domain_dims", type=float, nargs='+', default=[0.01, 4.0, 4.0, 0.0], help="Vector [dx, Lx, Ly, (Lz)].")
    parser.add_argument("--core_dims", type=float, nargs='+', default=[], help="Vector [width, height, depth].")
    parser.add_argument("--log_file", action="store_true", help="Enable logging to a file in addition to console.")

    # Parse Arguments
    args = parser.parse_args()

    # Prepare base directory path
    batch_dir = CWD / args.batch_dir / args.dim_mode / args.shape
    batch_dir.mkdir(parents=True, exist_ok=True)

    # Setup Logging
    log_file_path = None
    if args.log_file:
        timestamp_str = datetime.now().strftime('%Y%m%d_%H%M%S')
        log_filename = f"log_{timestamp_str}.txt"
        log_file_path = batch_dir / "logs" / log_filename
        log_file_path.parent.mkdir(parents=True, exist_ok=True)

    # Initialize logging
    setup_logging(log_file=log_file_path)

    # Date and System Info Header
    start_time = datetime.now()
    logging.info("="*60)
    logging.info(f"EXECUTION STARTED AT: {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
    logging.info(f"Host System: {os.name.upper()}")
    logging.info("="*60)

    # Verify base configuration file exists
    base_config_path = Path(args.base_config)
    if not base_config_path.is_file():
        logging.error(f"Base configuration file not found: {base_config_path}")
        exit(1)

    # Copy base configuration file
    dest_base_config_path = batch_dir / "configs" / "base_simulation_config.ini"
    dest_base_config_path.parent.mkdir(parents=True, exist_ok=True)
    if not dest_base_config_path.is_file():
        shutil.copy(base_config_path, dest_base_config_path)
    base_config_path = dest_base_config_path

    # Range of densities
    density_step = args.dens_step
    simulation_densities = np.arange(args.min_den, args.max_den + density_step, density_step)
    if args.densities and len(args.densities) > 0:
        simulation_densities = args.densities
    simulation_densities = [round(d, 2) for d in simulation_densities if 0.0 < d < 1.0]
    simulation_densities = sorted(list(set(simulation_densities)))

    # Seeds
    master_seed = 20260101 # Happy New Year 2026!
    rng = np.random.default_rng(master_seed)
    seeds = rng.integers(low=1, high=9999999999, size=args.num_seeds).tolist()

    # Build Meshes Configuration
    mesh_config = {}
    mesh_config["fibrosis_type"] = args.ftype
    mesh_config["dim_mode"] = args.dim_mode
    mesh_config["shape"] = args.shape
    mesh_config["domain_dims"] = args.domain_dims
    mesh_config["core_dims"] = args.core_dims
    if args.shape.lower() == "full":
        mesh_config["core_dims"] = []

    # Configuration Summary Log
    logging.info("--- CONFIGURATION SUMMARY ---")
    logging.info(f"Base Directory   : {batch_dir.resolve()}")
    logging.info(f"Config File      : {dest_base_config_path.name}")
    logging.info(f"Densities        : {simulation_densities}")
    logging.info(f"Fibrosis Type    : {args.ftype.upper()} ({args.dim_mode} - {args.shape})")
    logging.info(f"Random Seeds     : {args.num_seeds} seeds generated (Master: {master_seed})")
    logging.debug(f"Full Seed List   : {seeds}")
    logging.debug(f"Meshes Config    : {mesh_config}")

    if log_file_path:
        logging.info(f"Log File         : {log_file_path.name}")
    logging.info("-" * 30)

    # Batch Parameters
    batch_params = {
        'angles': args.angles,
        'densities': simulation_densities,
        'seeds': seeds,
        'mesh_config': mesh_config,
        'atpi_vals': args.atpi_vals,
        'generate_mesh': args.generate_mesh,
        'batch_dir': batch_dir,
        'base_config_path': base_config_path
    }

    # Run Batch Simulations
    try:
        run_simulation_batch(batch_params)
    except KeyboardInterrupt:
        logging.warning("\nBatch execution interrupted by user (Ctrl+C).")
        exit(1)
    except Exception as e:
        logging.critical(f"Fatal error during batch execution: {e}", exc_info=True)
        exit(1)

    end_time = datetime.now()
    duration = end_time - start_time
    logging.info(f"EXECUTION FINISHED AT: {end_time.strftime('%Y-%m-%d %H:%M:%S')}")
    logging.info(f"TOTAL DURATION: {duration}")
